version: '3.8'

services:
  db:
    image: mysql:8.0.36
    container_name: db-psa
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: psa
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - mysql-psa:/var/lib/mysql
      - ./psa.sql:/docker-entrypoint-initdb.d/psa.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --silent" ]
      interval: 20s
      timeout: 8s
      retries: 10

  seeder:
    build: .
    container_name: go-seeder
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: psa
      TZ: America/Argentina/Buenos_Aires
    command: [ "./main" ]

volumes:
  mysql-psa:
